### PR TITLE
CI: Add macOS

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
With macOS platform, it waits a long time for booting VM.

Pending

**Comment by mockdeep** [comment]
@Watson1978 how long does it take? I don't see much time on the checks.

**Comment by mockdeep** [comment]
@Watson1978 bump on my question ^^

**Comment by Watson1978** [comment]
@mockdeep 
The number of parallel VMs available on macOS seems to be limited. (Maybe, it is 4~5).
waited 20~30 minutes to finish running all spec with limited resources.

**Comment by mockdeep** [comment]
@Watson1978 what if we reduce the number of builds on MacOS and test the 2 most recent versions of ruby and 2 most recent versions of ImageMagick?

**Comment by Watson1978** [comment]
@mockdeep Sounds good to me. The most of specs have been verified on linux, so I think it will be enough.

**Pull request closed without merging**
