### PR TITLE
Release: bump version, update changelog

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by dlemstra** [comment]
Has the plan to release `rc3` first been dropped? Don't mind going to `4.1.0` but I wanted to make sure this is a deliberate choice.

**Comment by mockdeep** [comment]
@dlemstra I'm open to doing `rc3` if you think that's appropriate. It seemed like a lot of fixes went into this most recent release, but maybe it's worth releasing another release candidate just to be safe.

**Comment by Watson1978** [comment]
I don't think a lot of people will use RC3 if we release it.

RC2 has been downloaded 4000 times.
https://rubygems.org/gems/rmagick/versions/4.1.0.rc2

However, I think any major problems were not reported with it.

Even if we release RC3, it will find a lot of problems after major releases because a lot of people will use it...

**Comment by mockdeep** [comment]
Okay, we'll go ahead and release `4.1.0`, then. `rc2` has been out for 6 months, so if that hasn't been downloaded much, then we're probably not going to see much from `rc3`.

**Pull request merged**
