### PR TITLE
Refactor error handling

### PR DESCRIPTION
**Pull request by dlemstra**
This PR makes some changes to the error handling code by removing some duplicate and unused code.

### CODE REVIEW

**Comment by mockdeep** [comment]
Hey @dlemstra this looks like it might be a good candidate for breaking up into multiple PRs. Do you mind splitting it out?

**Comment by dlemstra** [comment]
How would you like me to split this up? I could do the removing of the argument in a separate PR but I don't know how useful that will be.

**Comment by mockdeep** [comment]
Yeah, I think that would be good at least. Maybe pulling out the `format_exception` helper, too.

**Comment by dlemstra** [comment]
These changes need to be made after each other so that will take me 3 pull request that need to wait on each other before they can be created. Here is the first one: #512.

**Pull request closed without merging**
