### PR TITLE
CI: Update ImageMagick

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by dlemstra** [comment]
There was a bug in our `draw` code in this release so you probably want to wait for the next release.

**Comment by Watson1978** [comment]
OK, I see. thanks :)

**Comment by dlemstra** [comment]
Maybe we could also include one build with the master branch of im6 and im7 to run the test and detect this earlier?

**Comment by Watson1978** [comment]
Sounds good :)

**Comment by mockdeep** [comment]
TravisCI has [a cron feature](https://docs.travis-ci.com/user/cron-jobs/) that we might be able to use to run nightly builds against IM master. That way it wouldn't necessarily need to block any other code changes when the build fails.

**Comment by dlemstra** [comment]
18 is a broken release. We are now working on a new release.

**Comment by Watson1978** [comment]
@dlemstra Can you tag the latest version in ImageMagick repository?

**Pull request merged**
