### PR TITLE
CI: Update ImageMagick versions

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
Hmm, latest ImageMagick 7.0.9 fails the spec on Windows + old Ruby platform...

@dlemstra Do you know the reason?

**Comment by dlemstra** [comment]
Don't think it fails because of the old Ruby platform. It stops executing the tests once one of the tests fails. But I have no idea why this fails. In my Magick.NET library I have a test that is very similar to this test and I tried it with the commit of the release and this does not fail.

**Comment by dlemstra** [comment]
It looks like I was running my tests incorrectly (prob older version of the ImageMagick code). I can now reproduce the issue in my unit tests and I am working on a fix.

**Comment by Watson1978** [comment]
Thanks !!!

**Pull request merged**
