### PR TITLE
Always use lowercase profile names to fix issues with ancient versions of ImageMagick.

### PR DESCRIPTION
**Pull request by dlemstra**

### CODE REVIEW

**Comment by Watson1978** [comment]
I tried this PR with following code. However, Image#iptc_profile still returns `nil`. This PR will fix another problem? 🤔 

```ruby
require './RMagick2.so'


img = Magick::Image.new(10, 10)
img.iptc_profile = 'xxx'

puts Magick::Long_version
puts "-" * 80
p img.iptc_profile
```


```
$ ruby rmagick.rb
This is RMagick 3.0.0 ($Date: 2009/12/20 02:33:33 $) Copyright (C) 2009 by Timothy P. Hunter
Built with ImageMagick 6.7.7-10 2019-04-09 Q16 http://www.imagemagick.org
Built for ruby 2.3.8
Web page: http://rmagick.rubyforge.org
Email: rmagick@rubyforge.org
--------------------------------------------------------------------------------
nil
```

**Comment by dlemstra** [comment]
This PR was based on an assumption. Had some issues with casing in the past. Will need to do some more testing to make sure this works.

**Comment by Watson1978** [comment]
OK, I also investigate the issue. Thanks

**Comment by dlemstra** [comment]
Might also be nice to add something called `Image_each_profile_name` to get the names of all the profiles in the image? This will probably give you some extra information.

**Comment by dlemstra** [comment]
I did not read `Image_each_profile` properly and notice that it already returns the name. And it turns out that my fix was incorrect and this PR should be closed. For more info see `#554`.

**Pull request closed without merging**
