### PR TITLE
Add set quantum operator

### PR DESCRIPTION
**Pull request by dlemstra**
This PR adds `SetQuantumOperator` and updates one of the examples to use this instead.

### CODE REVIEW

**Comment by Watson1978** [comment]
Seems different image generated.

## With master brunch + RMagick 3.2.0

crop_with_gravity

## With your PR

crop_with_gravity

**Comment by dlemstra** [comment]
Thanks for testing this. Will need to take a better look on why the image is not changed. Which ImageMagick version did you use?

**Comment by Watson1978** [comment]
> Which ImageMagick version did you use?

Used ImageMagick 6.9.10-49 for both images.

**Comment by dlemstra** [comment]
I forgot to activate the alpha channel before setting it.

**Pull request merged**
