### PR TITLE
Morphology

### LINKED ISSUE #21: support for ImageMagick morphology option
<a href="https://github.com/goodwillta"></img></a> **Issue by [goodwillta](https://github.com/goodwillta)**
_Tuesday Nov 01, 2011 at 08:15 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/35_

----

morphology option is powerful and extremely handy, and has been available since ImageMagick 6.6.0-1. Are there any plans to include the option in rmagick? It would be greatly appreciated.

### PR DESCRIPTION
**Pull request by vassilevsky**
Copy of https://github.com/rmagick/rmagick/pull/40

We really need to merge this awesome contribution by @naquad. But it has no tests. @mockdeep, could you cover this with RSpec?

To update this changeset, please open pull requests to the `morphology` branch.

Closes #21 and #24.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 1330c826cbc4b15171a9f1221792dbef63de3719
  * Your subject line is longer than 72 characters

Guidelines are available at http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

---
This message was auto-generated by https://gitcop.com

**Comment by mockdeep** [comment]
@vassilevsky we'll need to get [this one](https://github.com/gemhome/rmagick/pull/176) merged first, though the build might still be busted.

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: 6a4b4aa4b3e447e280a04c3c39be5368afef9824
  * Your subject line is longer than 72 characters

Guidelines are available at http://robots.thoughtbot.com/5-useful-tips-for-a-better-commit-message

---
This message was auto-generated by https://gitcop.com

**Comment by vassilevsky** [comment]
I have rebased it on the latest `master`. It is ready to be specced.

**Comment by vassilevsky** [comment]
Closing this because pull requests need to be pointed at the new `develop` branch. Also, it needs tests.

**Comment by mockdeep** [comment]
So what's going on with the `develop` branch then?

**Comment by vassilevsky** [comment]
I think we should keep master at the last release at all times. Everything that's done after the last release goes into the develop branch. You can always see what's new with `git log master..develop`. When there are changes worth releasing, merge develop into master, add a commit with new version and changelog, and release. I'm gonna do this now.

**Comment by linduxed** [comment]
Sounds like a good idea.

**Comment by mockdeep** [comment]
What are the benefits of running on a `develop` branch instead of `master`? I can see it's nice for people coming to the repo to see the most recent deployed version of the readme. One downside is that contributors will have to remember to pull request to the `develop` branch and we'll have to let new contributors know as well.

**Comment by vassilevsky** [comment]
When `master` has new unreleased stuff it can be confusing for people. Not everyone knows that you need to expand the drop-down and choose the latest tag to see repo contents as they are in the latest released gem version.

I have added information about the `develop` branch to `CONTRIBUTING.md`. GitHub links to it at the top of new issue or PR. Hope that helps.

This is basically an optimization for users rather than developers.

**Comment by mockdeep** [comment]
Okay, sounds good.

**Comment by vassilevsky** [comment]
It has value even though it doesn't have tests. Will merge this and see what happens.

**Pull request merged**
