### PR TITLE
Fix bug of signal handling internally

### PR DESCRIPTION
**Pull request by Watson1978**
The signal handler settings have a system-wide impact.
It seems that in some cases the app won't work properly if it just restore the signal handling to the default.

At least, the gem of CarrierWave gem is failed with RMagick 4.1.0.

To make more safety, this patch restores the handlers that had been configured instead of restoring the defaults.

Related https://github.com/rmagick/rmagick/pull/1072

### CODE REVIEW

**Comment by Watson1978** [comment]
I tried CarrierWave with following change.
```
  if RUBY_ENGINE != 'jruby'
    s.add_development_dependency "rmagick"
  end
```
in https://github.com/carrierwaveuploader/carrierwave/blob/d41ad71ad71a813dddf47e750e5a8b5f5c8d4e0d/carrierwave.gemspec#L45

**Comment by Watson1978** [comment]
@mockdeep I think this fix is critical.
So, I want to release RMagick v4.1.1 with this PR.

**Comment by mockdeep** [comment]
@Watson1978 version 4.1.1 has been released.

**Comment by Watson1978** [comment]
@mockdeep Thankyou so much!!

**Pull request merged**
