### PR TITLE
CI: Update ImageMagick

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
@dlemstra Can you know why `test_issue_604` was failed with ImageMagick 6.9.10-70 ?

```
  1) Error:
DrawUT#test_issue_604:
Magick::ImageMagickError: unable to open image `1': No such file or directory @ error/blob.c/OpenBlob/2881
    /home/travis/build/rmagick/rmagick/test/Draw.rb:346:in `draw'
    /home/travis/build/rmagick/rmagick/test/Draw.rb:346:in `test_issue_604'
```

**Comment by dlemstra** [comment]
We have found the problem and now we need to figure out how to fix this. Will get back to you when I have more info.

**Comment by Watson1978** [comment]
@dlemstra Can you add the release tags in https://github.com/ImageMagick/ImageMagick6/tags for new 6.9.10-xx versions ?

**Comment by dlemstra** [comment]
The tags for `7.0.9-7` and `6.9.10-77` have been added.

**Pull request merged**
