### PR TITLE
Remove old Ruby version support

### PR DESCRIPTION
**Pull request by mockdeep**
These are the vesions that are currently covered in [Ruby's maintenance
branches][mb].

[mb]: https://www.ruby-lang.org/en/downloads/branches/

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 does this seem reasonable to you?

**Comment by Watson1978** [comment]
The latest macOS still has bundled Ruby 2.6 by default. So, I think Ruby 2.6 may be useful to remain.

**Comment by mockdeep** [comment]
Yeah, it seems like we could probably remove 2.6 as well. RuboCop only supports >= 2.7, so we won't be able to upgrade that to the latest unless we deprecate 2.6.

**Comment by mockdeep** [comment]
Going to close this one for now. I'll reopen once version 5 has been stable for a little longer.

**Pull request closed without merging**
