### PR TITLE
RSpec: flesh out channel_mean_spec

### PR DESCRIPTION
**Pull request by Le1gh**

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 @dlemstra any idea why the stddev would be different by 10-15 between IM 6.8 and 6.9?

**Comment by Watson1978** [comment]
It seems to fail the test since ImageMagick 6.9.0.

I think this behavior is dependent on ImageMagick.
But I wonder whether we need to test...
I think it would be better to test the behavior of RMagick.

**Comment by mockdeep** [comment]
I think it's worth testing ImageMagick just a little, since they don't really have much in the way of tests. It'll help us keep RMagick more stable and reliable if we can report issues back to ImageMagick quickly.

What's confusing to me about this, though, is that I wouldn't expect stddev to be the sort of thing that would vary between versions. I guess maybe there was a bug in earlier versions. We can add an `unsupported_before`.

**Comment by Watson1978** [comment]
OK, I see. Yeah, unsupported_before is useful in this case ;)

**Pull request merged**
