### PR TITLE
Test if RuboCop on Semaphore detects this

### PR DESCRIPTION
**Pull request by vassilevsky**
This is what I meant when I said it would be nice to run RuboCop as a different check.

There are plenty CI services with free offerings for open source. One of the best ones is Semaphore. I've set up a project there that simply runs the latest RuboCop against the repo.

### CODE REVIEW

**Comment by mockdeep** [comment]
One problem with this is that the checks will fail if they end up out of sync with our bundled version. Can you just run `bundle` instead?

**Comment by vassilevsky** [comment]
My idea was to remove `rubocop` from the bundle and just always use the latest version.

When a new version is released, and new/changed cops yield failures, we can either:
* modify `.rubocop.yml` to silence them, or
* fix the issues in actual code.
The second option is more preferable :)

**Comment by mockdeep** [comment]
The problem I see is that it will have effects on unrelated code. So, for example, my branch with the spec updates failed because the rubocop version changed, when really it shouldn't have. I think it's nice to lock down for the most consistent experience, where the same commit will consistently pass or fail regardless of outside gem updates.

**Comment by vassilevsky** [comment]
Your argument is valid.

**Comment by vassilevsky** [comment]
Current commands:

```
bundle install --path=vendor/bundle
bundle exec rubocop --display-cop-names
```

**Comment by mockdeep** [comment]
Cool sounds good.

**Pull request closed without merging**
