### PR TITLE
Release: bump version, update changelog

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
@mockdeep If there are no problems, could you please release this?

**Comment by dlemstra** [comment]
Do we have any other pending breaking changes? Might be a good idea to include them in this release?

**Comment by mockdeep** [comment]
There are some more deprecations in the code. Should we try to clean up the code more before the next release?

**Comment by Watson1978** [comment]
I agree with removing the deprecated code.

**Comment by Watson1978** [comment]
At least I no longer have deprecated things.

**Comment by mockdeep** [comment]
:fireworks:

**Comment by mockdeep** [comment]
RMagick 5.0.0 has been released!

**Comment by Watson1978** [comment]
Thanks😘

**Pull request merged**
