### PR TITLE
Use Ruby's allocator to solve huge memory usage with ImageMagick 7

### PR DESCRIPTION
**Pull request by Watson1978**
ImageMagick 7 uses heap area allocated by `posix_memalign()` for cached image data internally.

```c
#if defined(MAGICKCORE_HAVE_POSIX_MEMALIGN)
  if (posix_memalign(&memory,alignment,extent) != 0)
    memory=NULL;
```
    
https://github.com/ImageMagick/ImageMagick/blob/62b1c449347b1a3ae3a9bcfae0407b30803ec9b9/MagickCore/memory.c#L274-L276

However, Ruby's GC doesn't know how much memory is acquired by using `posix_memalign()`.

To solve this issue, `SetMagickAlignedMemoryMethods()` API was added to ImageMagick at 7.0.9 to set and use user defined allocator.
https://github.com/ImageMagick/ImageMagick/commit/02c84c6540a428653bd0c5c3efd15ead9ba2411f

This PR will set Ruby's allocator using `SetMagickAlignedMemoryMethods()` to solve https://github.com/rmagick/rmagick/issues/817 

----

The graph below shows the memory usage after changing.

SetMagickAlignedMemoryMethods

### CODE REVIEW

**Comment by mockdeep** [comment]
Wow, great work @Watson1978! It looks like the failures might be bugs in ImageMagick:

```
coders/webp.c:764:3: error: unknown type name ‘WebPAnimEncoderOptions’

   WebPAnimEncoderOptions

   ^

coders/webp.c:768:3: error: unknown type name ‘WebPAnimEncoder’

   WebPAnimEncoder
```

**Comment by dlemstra** [comment]
Will take a look at those build errors tonight or tomorrow.

**Comment by dlemstra** [comment]
We just pushed a patch to the ImageMagick repository that should resolve the building issue.

**Comment by dlemstra** [comment]
ImageMagick 7.0.9-1 has been released and that should solve the build issue.

**Pull request closed without merging**
