### PR TITLE
CPPCheck: reduce scope of variables in more files

### PR DESCRIPTION
**Pull request by mockdeep**
Some of these might be able to in-line the assignment but I don't know
the C code well enought to judge the best format.

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 I'm seeing a lot of builds stalling. Have you been having this problem?

**Comment by mockdeep** [comment]
@Watson1978 it looks like the Windows build is no longer working for some reason:

```
gmake: *** No rule to make target '/D/rubyinstaller-2.4.9-1-x64/include/ruby-2.4.0/ruby.h', needed by 'rmagick.o'.  Stop.
```

I'm seeing it on [my other branch as well](https://github.com/rmagick/rmagick/pull/1017), so it doesn't appear to be related to code changes. Any idea what is happening?

**Comment by Watson1978** [comment]
Previously, `C:\msys64\usr\bin/make.exe` was used to build RMagick.
Now, `C:\Strawberry\c\bin/gmake.exe` is used in Windows platform...

Seems that something was changed in CI.

I will investigate...

**Comment by Watson1978** [comment]
I added a workaround with https://github.com/rmagick/rmagick/pull/1021

**Comment by mockdeep** [comment]
Great, thanks @Watson1978!

**Pull request merged**
