### PR TITLE
Change indentation style follow ruby style guide (2 spaces)

### PR DESCRIPTION
**Pull request by marceloboeira**
As mentioned at #210 

Refactor based on style-guides: 
* https://github.com/styleguide/ruby
* https://github.com/bbatsov/ruby-style-guide

PS: There's a lot more to be done!

### CODE REVIEW

**Comment by vassilevsky** [comment]
Strange... I'm pretty sure I already did something like this...

Whatever. Thanks Marcelo!

**Comment by marceloboeira** [comment]
@vassilevsky thank you! I saw some other problems along the code that I want to investigate, most of it are silly, but maybe still dangerous.

**Comment by linduxed** [comment]
Thanks for contributing!

**Comment by marceloboeira** [comment]
@linduxed :+1:

**Pull request merged**
