### PR TITLE
Fix build error with Ruby 3.1 on macOS

### PR DESCRIPTION
**Pull request by Watson1978**
https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/

This patch will avoid build error at https://github.com/rmagick/rmagick/issues/1314

Close https://github.com/rmagick/rmagick/issues/1314

### CODE REVIEW

**Review by dlemstra — APPROVED** [review]

**Comment by Watson1978** [comment]
I guess that this requires https://github.com/ruby/setup-ruby/pull/250 to avoid error in macos

**Comment by Watson1978** [comment]
Hmm, need to fix https://github.com/rmagick/rmagick/issues/1314

**Comment by Watson1978** [comment]
The behavior of mkmf in Ruby 3.1 seems to have changed. If we set the compiler flag about ImageMagick in $CFLAGS, calling methods such as have_header will cause an error....

**Comment by Watson1978** [comment]
@mockdeep Can you release this patch as Ruby 3.1 support ?

**Comment by mockdeep** [comment]
@Watson1978 sure, will do.

**Comment by mockdeep** [comment]
Released!

**Comment by Watson1978** [comment]
Thanks !!

**Pull request merged**
