### PR TITLE
CI: Build old versions of ImageMagick once

### PR DESCRIPTION
**Pull request by dlemstra**
Yesterday #497 was merged to reduce the builds but #340 reverted part of those changes. I don't think it will be necessary to build all combinations of Ruby and ImageMagick. This patch removes the duplicate builds and makes the build a lot faster again.

### CODE REVIEW

**Comment by mockdeep** [comment]
@dlemstra I mentioned it in the other PR, but I think it's important that we build across versions and combinations. I know it slows the build down, but we've seen several bugs that have manifested on only a single combination of Ruby and ImageMagick versions, so I think it's worth handling all of them to avoid regressions, optimizing for correctness over performance. Maybe @Watson1978 will have some additional thoughts.

**Comment by dlemstra** [comment]
Do you have some examples? I don't understand why one version of ImageMagick would behave differently accross Ruby versions.

**Comment by mockdeep** [comment]
@dlemstra sure! It seems like most of the issues come from some changes in the way that Ruby manages memory and the stack across versions. We've had a [lot of problems with the `monitor` feature](https://github.com/rmagick/rmagick/issues/464), and still haven't quite fixed it, yet. Here are some PRs:

https://github.com/rmagick/rmagick/pull/339
https://github.com/rmagick/rmagick/pull/462
https://github.com/rmagick/rmagick/pull/467
https://github.com/rmagick/rmagick/pull/468

We saw an issue when Ruby released [version 2.4.5 from 2.4.4](https://github.com/rmagick/rmagick/pull/467#issuecomment-472944747), and for some reason there was a build that failed [with hdri but not without](https://github.com/rmagick/rmagick/pull/468#issuecomment-473004621). Here are a couple of TravisCI builds that have only failed on a particular version of Ruby:

2.4: https://travis-ci.org/rmagick/rmagick/builds/506357202
2.5: https://travis-ci.org/rmagick/rmagick/builds/494272977

I haven't been very active in a couple of weeks, but I'd like to spend a lot more time refactoring the codebase, and an important part of that is feeling very confident that I haven't triggered an obscure edge case in some combination of the versions that we support. It sucks that our builds take so long, and TravisCI seems to stall sometimes, which makes it worse, but it's important to me to make sure that we're covering all of our bases and ensuring that nothing is able to creep in.

**Comment by dlemstra** [comment]
I now understand why you want to build both the normal version and hdri version for every ruby version. But why should we build all the old versions of ImageMagick for every ruby version? I think it will be sufficient to only build the older versions with Ruby 2.6.

**Comment by mockdeep** [comment]
@dlemstra So with [this build](https://travis-ci.org/rmagick/rmagick/builds/506357202) it only failed ImageMagick 6.8 against Ruby 2.4, and [this one](https://travis-ci.org/rmagick/rmagick/builds/494272977) against Ruby 2.5, so we wouldn't have seen those if we had only been testing against 2.6 for ImageMagick 6.8.

It *shouldn't* fail, but I'm constantly surprised about how code finds interesting ways to fail, so I'm in favor of testing as many combinations as possible to ensure that nothing slips through the cracks.

**Comment by dlemstra** [comment]
This builds are related to the Ruby version and not to the ImageMagick version. You would also have caught that error if the build was done with IM 6.9 instead. I have updated this PR according to your comments. 

This PR now builds IM 6.9.10-35 with HDRI enabled and disabled for all Ruby versions. But for the older versions of IM it will only be tested on the latest version of Ruby with both HDRI enabled and disabled. Doing the latter for all Ruby versions will probably only delay the build and not catch anything extra. In the examples that you stated the only thing that affected the build result was the version of Ruby and not the version of ImageMagick.

Can you help us make a decision @Watson1978?

**Comment by Watson1978** [comment]
I think we should not drop older ImageMagick while we stay in Rmagick v3.x to guarantee the quality.

**Comment by dlemstra** [comment]
We won't drop older version of ImageMagick we just don't test them with every ruby version.

**Comment by Watson1978** [comment]
> We won't drop older version of ImageMagick we just don't test them with every ruby version.

SO, I mean we should test all combination we supported

**Comment by mockdeep** [comment]
@dlemstra we don't actually know if those builds would have failed against 6.9, since we weren't testing against 6.9 at that time, but I guess that undermines both of our points on that front. One additional use case to keep in mind is that we [sometimes backport features](https://github.com/Watson1978/rmagick/blob/d866548a5a351380f559d31808c7cc33d82b9ac3/ext/RMagick/rmimage.c#L7164-L7179) for older versions of ImageMagick. Ruby internal APIs are prone to change, though, so it's important we test such code against multiple versions of Ruby to ensure the code is compatible across all of them.

**Comment by dlemstra** [comment]
I understand your concern. I do think you are really touching an edge case there and it is not very likely that your example would behave differently across Ruby versions. 

Maybe it would be possible to test every combination conditionally? For example only when the master is build and do the minimum in a PR build? But that should be something for another PR.

**Comment by mockdeep** [comment]
@dlemstra I think rather than trying to reduce the number of builds, we should focus on finding ways to speed up the build. It would pretty annoying to have a build pass on a PR only to fail on master after it had been merged. Then we'd have to revert or follow up on it.

**Pull request closed without merging**
