### PR TITLE
Update RuboCop to latest 0.50 supported by ruby 2.0

### PR DESCRIPTION
**Pull request by ShockwaveNN**
Fix error on semaphoreci check:
`test/Image2.rb:447:20: E: literal contains escape sequences incompatible with UTF-8`

### CODE REVIEW

**Comment by ShockwaveNN** [comment]
@vassilevsky I think I'm done
Test results seems same as in https://github.com/rmagick/rmagick/pull/297 (3 failed case)
I split all configs to 
`.rubocop.yml` - preferred code style which should not be changed to keep compability with ruby 2.0 (and maybe earlier) and not to break stuff
`.rubocop_todo.yml` - code style which should be fixed in future, but may cause incompatible API changes or some other gem breaking changes, but I think it still need to be fixed, but not ASAP

**Comment by vassilevsky** [comment]
Thank you very much, Pavel. You've definitely made code better.

**Comment by ShockwaveNN** [comment]
@vassilevsky good to hear that my PR left unnoticed. Glad to help :)
I think I cant start a new round since rubocop is 0.59.2 by now :)

**Comment by ShockwaveNN** [comment]
@vassilevsky oh, I forgot that I used Rubocop 0.50.0 since it's latest supported by Ruby 2.0
So my work here is done :)

**Comment by vassilevsky** [comment]
I'm planning to release v3 with many potentially breaking changes. That's why I merge all PRs. You may drop Ruby 2.0 support if that's what's stopping you.

**Comment by ShockwaveNN** [comment]
@vassilevsky if so I think you should start by dropping support of ruby 2.0 in https://github.com/joneslee85/rmagick/blob/develop/lib/rmagick/version.rb
Without it I think RuboCop will complain about `.gemspec` in other case.
After that I'm ready to introduce new rubocop.

**Comment by ShockwaveNN** [comment]
BTW - latest RuboCop seems supported only by Ruby 2.2 https://github.com/rubocop-hq/rubocop/blob/master/rubocop.gemspec#L12 so if you really ready to full RuboCop action you should drop 2.1 also :) But I think I can mange working with 2.1 if I remember correctly

**Comment by vassilevsky** [comment]
https://www.ruby-lang.org/en/downloads/

It says that even 2.2 is no longer supported. But it's still alive. 2.1 is not, so it's safe to drop it.

I've pushed the new requirement to `develop`.

**Comment by ShockwaveNN** [comment]
@vassilevsky yep, you totally right, 2.3 is oldest current supported MRI Ruby. 
I take a look at rubocop with 2.1 in near time, thanks

**Pull request merged**
