### PR TITLE
Release: bump version, update changelog

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 the Windows build on this seems kind of flaky. I've re-run it a couple of times.

**Comment by Watson1978** [comment]
The following spec seems as unstable as ever...

https://github.com/rmagick/rmagick/blob/60f613e3d0b5dc0449868ad3d90920a83ee66b59/spec/rmagick/kernel_info/class_methods/builtin_spec.rb#L2

**Comment by Watson1978** [comment]
I think the problem will be solved after rebasing with master.

I added one fixing for Freebsd problems (#1203).
Can you add it to changelog?

**Comment by mockdeep** [comment]
Alright, I've update the branch. If it passes, I'll release version 4.1.2 tomorrow.

**Comment by mockdeep** [comment]
RMagick 4.1.2 is live.

**Pull request merged**
