### PR TITLE
CI: add Ruby 2.6 to CI checks

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by mockdeep** [comment]
Weird, @Watson1978 it looks like the new ruby `2.4.5` release broke for us. Got a `SEGV`.

**Comment by mockdeep** [comment]
https://travis-ci.org/rmagick/rmagick/jobs/506357204

**Comment by Watson1978** [comment]
Hmmm, ok I will see it

**Comment by Watson1978** [comment]
Unfortunately, seems `rm_progress_monitor()` is still weak. I guess this is related to Ruby's GC. 

```ruby
require './RMagick2.so'

monitor = proc do |mth, q, s|
  true
end

GC.stress = true

100.times do
  img = Magick::Image.new(2000, 2000) { self.monitor = monitor }
  img.resize!(20, 20)
  img.monitor = nil
end
```

```
$ ruby -v test.rb
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]
test.rb:11: [BUG] Segmentation fault at 0x00007f41fab0b000
ruby 2.4.5p335 (2018-10-18 revision 65137) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0005 p:---- s:0021 e:000020 CFUNC  :resize!
c:0004 p:0034 s:0015 e:000014 BLOCK  test.rb:11 [FINISH]
c:0003 p:---- s:0011 e:000010 CFUNC  :times
c:0002 p:0041 s:0007 E:000b68 EVAL   test.rb:9 [FINISH]
c:0001 p:0000 s:0003 E:001410 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
test.rb:9:in `<main>'
test.rb:9:in `times'
test.rb:11:in `block in <main>'
test.rb:11:in `resize!'

-- Machine register context ------------------------------------------------
 RIP: 0x000055c160e70c6d RBP: 0x00007f41f8c7c7c0 RSP: 0x00007f41f8c7c790
 RAX: 0x00000017a74cae00 RBX: 0x00007f41fab0b000 RCX: 0x0000000000000000
 RDX: 0x0000000000000000 RDI: 0x000055c1619925e0 RSI: 0x0000000000000000
  R8: 0x000055c160e70ec1  R9: 0x0000000000000000 R10: 0x00007f41f40008d0
 R11: 0x0000000000000000 R12: 0x00000017a74cadff R13: 0x0000000000000008
 R14: 0x000055c161b7b770 R15: 0x0000000000000002 EFL: 0x0000000000010206

-- C level backtrace information -------------------------------------------
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_print_backtrace+0x19) [0x55c160fcff5d] vm_dump.c:716
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_vm_bugreport+0xa4) [0x55c160fd03c4] vm_dump.c:986
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_bug_context+0x114) [0x55c161040769] error.c:510
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(sigsegv+0x5e) [0x55c160f4a41b] signal.c:907
/lib/x86_64-linux-gnu/libpthread.so.0 [0x7f42010e2890]
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(mark_locations_array+0x17) [0x55c160e70c6d] gc.c:3990
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(gc_mark_locations+0x4b) [0x55c160e70cec] gc.c:4004
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(mark_stack_locations+0x2f) [0x55c160e71305] gc.c:4215
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(mark_current_machine_context+0xc2) [0x55c160e7126b] gc.c:4197
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(gc_mark_roots+0xf3) [0x55c160e725d7] gc.c:4761
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(gc_marks_finish+0x53) [0x55c160e7337a] gc.c:5413
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(gc_marks_rest+0x49) [0x55c160e73910] gc.c:5558
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(gc_rest+0x92) [0x55c160e75a25] gc.c:6428
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(garbage_collect+0x25) [0x55c160e756d3] gc.c:6319
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(newobj_slowpath+0xbc) [0x55c160e6c540] gc.c:1877
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(newobj_slowpath_wb_protected+0x4c) [0x55c160e6c61b] gc.c:1895
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(newobj_of+0xdf) [0x55c160e6c752] gc.c:1927
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_wb_protected_newobj_of+0x36) [0x55c160e6c7ea] gc.c:1943
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(str_alloc+0x1d) [0x55c160f589af] string.c:690
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(str_new0+0x46) [0x55c160f58a19] string.c:712
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(str_new+0x2d) [0x55c160f58c26] string.c:732
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_str_new+0x2a) [0x55c160f58c52] string.c:738
/home/watson/.rbenv/versions/2.4.5-debug/bin/ruby(rb_str_new_cstr+0x36) [0x55c160f58d9e] string.c:773
/home/watson/prj/rmagick/ext/RMagick/RMagick2.so(rm_progress_monitor+0x6f) [0x7f41ff9003ac]
[0x7f41ff31ddac]
[0x7f41ff326c78]
[0x7f41fdc9097e]
/lib/x86_64-linux-gnu/libpthread.so.0(start_thread+0xdb) [0x7f42010d76db]
[0x7f420062688f]

-- Other runtime information -----------------------------------------------

...
```

**Comment by Watson1978** [comment]
Hｍｍｍ，It seems that there are still problems....😫

**Pull request merged**
