### PR TITLE
Added check to make sure that the type of the item in the array…

### PR DESCRIPTION
**Pull request by dlemstra**
This PR fixes the memory leak discussed in #800 and #808.

### CODE REVIEW

**Comment by Watson1978** [comment]
This PR fails tests

**Comment by Watson1978** [comment]
With `(CLASS_OF(new_pixel) != Class_Pixel)`, it should destroy `exception` and raise Ruby exception.

**Comment by dlemstra** [comment]
I did not realize that we already test for invalid values. But I am not sure what would be the best way to handle this. Ignoring the value instead of raising an exception would also seems like a valid solution for this situation. What would you prefer @mockdeep?

**Comment by mockdeep** [comment]
Hmm, if my understanding is correct, I guess I'd vote to raise a ruby exception so the user knows they're doing something wrong. If we have to check it anyway, we might as well communicate it back up to them.

**Pull request merged**
