### PR TITLE
CI: Update ImageMagick

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
@dlemstra With ImageMagick 6.9.12-35, the spec has been failed with following message. 
Do you know something what ImageMagick 6.9.12-35 was changed?

```
Failures:
  1) Magick::Draw#clip_path works
     Failure/Error: draw.draw(canvas)

     Magick::ImageMagickError:
       non-conforming drawing primitive definition `image' @ error/draw.c/RenderMVGContent/4410
     # ./spec/rmagick/draw/clip_path_spec.rb:29:in `draw'
     # ./spec/rmagick/draw/clip_path_spec.rb:29:in `block (2 levels) in <top (required)>'
```

https://github.com/rmagick/rmagick/runs/4910917220?check_suite_focus=true

**Comment by dlemstra** [comment]
I think I have found what is causing the issue. Will get back to you when I have more info.

**Comment by dlemstra** [comment]
Should be fixed in `7.1.0-22` and `6.9.12-37`.

**Comment by Watson1978** [comment]
> Should be fixed in 7.1.0-22 and 6.9.12-37.

Thank you so much!!

**Pull request merged**
