### PR TITLE
Added new enum values with the ImageMagick 7 names.

### PR DESCRIPTION
**Pull request by dlemstra**
This PR adds new enum values with the ImageMagick 7 names and alias for backwards compatibility. This PR also includes the removal of `Rec601LumaColorspace` and `Rec709LumaColorspace` that have been removed from ImageMagick 7.

### CODE REVIEW

**Comment by dlemstra** [comment]
I already added the aliases in Obsolete.rb? Can you clarify what you mean?

**Comment by Watson1978** [comment]
I add the tests for alias constants in https://github.com/rmagick/rmagick/pull/629

**Comment by dlemstra** [comment]
Oh sorry I did not realize you were referencing the test files. Will add those tests.

**Comment by Nakilon** [comment]
How am I supposed to fix the
```
NameError: uninitialized constant Magick::Rec601LumaColorspace
Did you mean?  Magick::Rec601YCbCrColorspace
```
?

**Pull request merged**
