### PR TITLE
Release the Global VM Lock on ImageList operations

### PR DESCRIPTION
**Pull request by vassilevsky**
Copy of #244 but the branch is now in this repo

### CODE REVIEW

**Comment by mockdeep** [comment]
Hey @Watson1978 would you mind taking a look at this? Is this something we should continue working on? If you think it is worthwhile, I can break it up into separate PRs.

**Comment by Watson1978** [comment]
If we can remove the GVL, it will introduce the better performance. However, I afraid the race condition by running multiple thread at same time. At least, we need the test code for this.

**Comment by mockdeep** [comment]
Okay, it sounds like maybe this is something we put off for a little while then until we have some better infrastructure.

**Comment by mockdeep** [comment]
I'm going to go ahead and close this for now. We'll probably want to revisit at some point, but it may be a while before we get a chance. In the meantime, we've got [an open issue for it](https://github.com/rmagick/rmagick/issues/243).

**Pull request closed without merging**
