### PR TITLE
Migrate to ImageMagick 7

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 if we can do this without breaking changes, I think we should try to do it as version 3.2 instead of 4.0. I'd love to avoid having two running versions to maintain, since we're going to need to maintain it for ImageMagick 6 for probably a couple more years.

**Comment by dlemstra** [comment]
You cannot avoid the breaking changes that have been made in ImageMagick 7. But the changes made in this PR are not compatible with ImageMagick 6 and that would mean that you would need to maintain two different branches or projects.

I am now working in a local branch where I try to use a different strategy than this PR. That branch can build with both ImageMagick 6 and ImageMagick 7 (work in progress) and create a different API based on the ImageMagick source that was used when this build started. 

But this does not solve the problem for version numbering the project. This project uses semver but I have an idea that could be used for this project. How about using the following strategy: `[IM_VERSION].[MAJOR].[PATCH]`. This mean that version `7.0.0` would be for IM7 and `6.0.0` for IM6. And if a breaking change is introduced in either (or one of them) the version would be bumped to `7.1.0`. And when a "normal" release is done the version will be bumped to `7.1.1`. Would this strategy be an option?

p.s. I love the work that has been done is this branch and I keep using it to check my local changes and make sure that I don't forget anything.

**Comment by mockdeep** [comment]
Can we talk more about the breaking changes between ImageMagick versions? Are there features that have been removed? I think if we're willing to put in the time we might be able to migrate forward without needing to have branching versions. For example, these are the scenarios I can imagine:

* **An existing API is removed:** We put in a deprecation warning and remove the feature in 4.0, or if we think it is important we implement it in RMagick. If we don't want to keep the feature, for people using 7.0 we can simply throw an error. This is not a breaking change, since we don't currently support 7.0 anyway.
* **An existing API is renamed:** We add an alias in our code and have a deprecation warning letting the user know they need to call new methods. We can maintain the new and the old one for a while and then eventually remove the old one.
* **An existing API changes functionality:** This one is tricky. Maybe we can continue to maintain the old behavior and have deprecations warning the user to change the way they use these methods. We would need to re-shape methods for different versions, which would suck.

I know it's probably a lot of work, but I think it will save us work and stress in the long run if we take the time to figure out how we can smoothly transition people between versions and avoid needing to maintain multiple releases.

**Comment by dlemstra** [comment]
You can find some information about what has been changed in ImageMagick 7 here: https://imagemagick.org/script/porting.php. In the ImageMagick project we decided to do a hard split because there have been so many internal changes. 

I don't think you can avoid having two releases, one linked with ImageMagick 7 and the other one linked with ImageMagick 6. The gem can only be linked with either ImageMagick 7 or ImageMagick 6. And that is why I purposed two different version ranges to make it much easier for our users to decide if they want to use ImageMagick 6 or 7.

But I do think we can make the transition not that complicated by trying to keep the API the same between version for most of the methods like this:

```c
VALUE
Image_signature(VALUE self)
{
    Image *image;
    const char *signature;
#if defined(IMAGEMAGICK_7)
    ExceptionInfo *exception;
#endif

    image = rm_check_destroyed(self);

#if defined(IMAGEMAGICK_7)
    exception = AcquireExceptionInfo();
    (void) SignatureImage(image, exception);
    CHECK_EXCEPTION()
    (void) DestroyExceptionInfo(exception);
#else
    (void) SignatureImage(image);
#endif
    signature = rm_get_property(image, "signature");
    rm_check_image_exception(image, RetainOnError);
    if (!signature)
    {
        return Qnil;
    }
    return rb_str_new(signature, 64);
}
```

And for a lot of methods that no longer have a channel suffix we can do this:

```c
VALUE
Image_separate(int argc, VALUE *argv, VALUE self)
{
    Image *image, *new_images;
    ChannelType channels = 0;
    ExceptionInfo *exception;

    image = rm_check_destroyed(self);
    channels = extract_channels(&argc, argv);

    // All arguments are ChannelType enums
    if (argc > 0)
    {
        raise_ChannelType_error(argv[argc-1]);
    }

    exception = AcquireExceptionInfo();
#if defined(IMAGEMAGICK_7)
    SET_CHANNEL_MASK(image, channels);
    new_images = SeparateImages(image, exception);
    RESTORE_CHANNEL_MASKS(image, new_images);
#else
    new_images = SeparateImages(image, channels, exception);
#endif
    rm_check_exception(exception, new_images, DestroyOnError);
    DestroyExceptionInfo(exception);
    rm_ensure_result(new_images);

    return rm_imagelist_from_images(new_images);
}
```

But yes there will be some breaking changes. The methods that now use `opacity` should be renamed to use `alpha` instead (https://imagemagick.org/script/porting.php#alpha).

Another approach would be using two branches like this PR started out but I think it would be much easier to only maintain one code base.

I personally think that my purposed approach is the easiest for the RMagick team and for our users. And I have been working on prototyping this for almost the whole last week. I will go back to my regular job next week so I cannot invest as much time as I did the last week but I would like to know if you and @Watson1978  can agree with this approach for making it possible to use ImageMagick 7 with RMagick.

**Comment by mockdeep** [comment]
@dlemstra I think the approach you're describing above would *not* require two branching RMagick versions, so we might actually be talking about the same idea. RMagick is compiled on the user's machine based on their currently installed ImageMagick version, so what you're doing with the pre-processor macros (`#if defined(IMAGEMAGICK_7)`) would happen on their machine. We don't need to have two different branching releases for that.

For the case of `opacity` -> `alpha`, are there functionality changes, or is it just a rename? If it's renaming, I think this would be a relatively straightforward transition. We can alias it for older versions of ImageMagick and add a deprecation warning in 3.x, then remove `opacity` in 4. If it changes functionality, we might still be able to change the `opacity` method to map parameters appropriately to the new `alpha` method.

By the way, thanks so much for using your time off to work on this project! I really appreciate how much you've put into it. You've already made a huge impact. Whatever you've built out towards ImageMagick 7 support I'm sure will be very valuable, even if we make adjustments to the final approach.

**Comment by dlemstra** [comment]
You are correct that you won't need two branches for the releases but I think it would be wise to publish a different release version based on the version of ImageMagick RMagick was linked with. If someone would report an issue with RMagick 7.x.x we would know that ImageMagick 7 was used. And if someone would use RMagick 6.x.x we would know that ImageMagick 6 was linked. We just have to make sure that we add this version strategy to the readme so people know that this project uses that version strategy.

ImageMagick 7 has switched to using alpha (0 = transparent) instead of opacity (QuantumRage is transparent). Alpha and opacity are two different things and I would advise against aliasing that or using the term opacity in RMagick that is linked with ImageMagick 7. If you have two versions of RMagick based on the version of ImageMagick having this difference in the API should not be an issue.

I would really like to know if the team could stand behind this strategy and implementation strategy (e.g. use `ifdef`) for using ImageMagick 7 with RMagick or tell me what kind of strategy you would want instead. I will stop working on the ImageMagick 7 branch that I have locally for now until we can agree on the strategy. And I would really like to know what @Watson1978 thinks about this strategy.

**Comment by Watson1978** [comment]
This PR shows how much changes will be required to migrate to ImageMagick 7.
If the change is as small as possible just mixing ImageMagick 6 and 7 code with `ifdef`, it might be better.

I still need to research a lot to think strategy to migrate...

**Comment by mockdeep** [comment]
I like the `ifdef` approach if we can make that work.

One way we can avoid confusion when it comes to users opening issues is by using [issue templates](https://help.github.com/en/articles/creating-issue-templates-for-your-repository). Projects like [eslint](https://github.com/eslint/eslint/issues/new?assignees=&labels=bug%2C+triage&template=BUG_REPORT.md&title=) and [rspec-rails](https://github.com/rspec/rspec-rails/issues/new) use them to request version information about dependencies from users for easier debugging.

**Comment by dlemstra** [comment]
Happy to hear that you both don't reject the ifdef approach. Will continue to work on that. The version strategy can be something for the future then. Will still take a while before that branch is donr. My primary concern for now is that the same version of the gem will have a different API. A version per ImageMagick major version can avoid that.

**Comment by mockdeep** [comment]
@Watson1978 can we close this or are there changes here you'd like to get in?

**Pull request closed without merging**
