### PR TITLE
CI: remove TravisCI in favor of CircleCI

### PR DESCRIPTION
**Pull request by mockdeep**
This moves *all* of the TravisCI checks over to CircleCI.

**Why**

- The builds run much more quickly on CircleCI. It took about 20 minutes
  to run on CircleCI and nearly an hour on TravisCI. This will get even
  better if we upgrade to [the Performance plan][1] on CircleCI, which
  eliminates queueing, so builds would instead take less than 5 minutes.
- I'd like to enable test coverage across all of the build jobs. This
  involves storing the test results and aggregating them together after
  all are finished. On TravisCI this would require uploading them to an
  external service like S3. CircleCI can preserve build artifacts for
  us, though, so we don't need another service.

[1]: support.circleci.com/hc/en-us/articles/360038512113-Does-CircleCI-Support-Private-and-Public-Repositories-

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 @dlemstra are there any objections to moving all of our Linux builds to CircleCI? The configuration is somewhat more complicated, but it's much faster and enables some additional functionality, such as SSHing into builds and collecting build artifacts, like test coverage.

**Comment by Watson1978** [comment]
Sounds good :)

**Comment by mockdeep** [comment]
Alright @Watson1978 this branch is passing on CircleCI. Once Appveyor is passing you should be able to merge it and rebase your branches.

**Comment by dlemstra** [comment]
Have you considered GitHub actions? Big fan of that. Maybe take a look at that in a new PR?

**Comment by mockdeep** [comment]
@dlemstra I've looked into it a couple of times and wasn't quite ready to make the leap for larger projects. Maybe it would work better for a smaller project like RMagick, though. I'll look into it. It looks like we can [store build artifacts](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts), which is what I was looking for with this change.

**Pull request merged**
