### PR TITLE
remove magick_command in extconf.rb

### PR DESCRIPTION
**Pull request by mockdeep**
It appears that `identify` is available on all versions of ImageMagick,
so maybe we can just use that?

### CODE REVIEW

**Comment by dlemstra** [comment]
It is possible that you only have the `magick` command for ImageMagick 7 so I don't think you should merge this PR.

**Comment by mockdeep** [comment]
Okie dokey.

**Comment by mockdeep** [comment]
@dlemstra when would `identify` not be available?

**Comment by dlemstra** [comment]
With the Windows installation it is possible that only `magick` is installed. I am not sure what happens on the various Linux distros.

**Pull request closed without merging**
