### PR TITLE
Remove deprecated Image#matte and Image#matte=

### PR DESCRIPTION
**Pull request by dlemstra**

### CODE REVIEW

**Comment by Watson1978** [comment]
We aim to release v4.0 at next?
If so, I can agree this.

However, I want we will add more tests before.

**Comment by dlemstra** [comment]
The plan is to release v4.0 next that only removes the deprecated code.

**Comment by Watson1978** [comment]
OK agreed. @mockdeep  How do you think about this?

**Comment by mockdeep** [comment]
Yeah, I think 4.0 makes sense as the next release. What tests do you want to add?

**Comment by Watson1978** [comment]
I want to add tests whether RMagick will generate same output with IM 6 and 7, maybe, until 4.1 ;)

**Pull request merged**
