### PR TITLE
CI: Update ImageMagick

### PR DESCRIPTION
**Pull request by Watson1978**

### CODE REVIEW

**Comment by Watson1978** [comment]
Seems `MPEG` is an unknown format with 7.0.10-31. 
https://github.com/rmagick/rmagick/pull/1231/checks?check_run_id=1199111529

@dlemstra Do you know whether this is expected behavior?

**Comment by dlemstra** [comment]
The MPEG coder has been replaced with the VIDEO coder.

**Comment by Watson1978** [comment]
Thank you for your quick response. OK, I will fix RMagick's test code.

**Comment by Watson1978** [comment]
Seems that setup script (before_install_linux.sh) cannot build IM 7.0.10-32.
I'm guessing this is related to https://github.com/rmagick/rmagick/issues/1228#issuecomment-700260450

@dlemstra Do you know how to avoid this error?

**Comment by dlemstra** [comment]
It's strange that you are getting this error. Building without the `WMF` encoder should resolve this issue and fixed the issue in the `Dockerfile` that you had earlier. Is it possible to create a new image that demonstrates this issue?

**Comment by Watson1978** [comment]
@dlemstra The Dockerfile is in https://gist.github.com/Watson1978/dbeb913aedd3c8e7b87bd9c8c7524b09 to reproduce.
It just removed `libmagickwand-dev` package from first version.

**Comment by dlemstra** [comment]
Version 7.0.10-32 has `--disable-shared` enabled by default. We will publish a new release to fix this soon.

**Comment by Watson1978** [comment]
hmm, 6.9.11-35 and 7.0.10-35 have changes about CMYK color...

```
2020-11-03T05:30:53.0831879Z   1) Magick::Image#get_pixels supports CMYK color
2020-11-03T05:30:53.0832968Z      [31mFailure/Error: [0m[32mexpect[0m(pixel.cyan).to    equal([1;34m49[0m  * [1;34m257[0m)[0m
2020-11-03T05:30:53.0833479Z      [31m[0m
2020-11-03T05:30:53.0833905Z      [31m  expected #<Fixnum:25187> => 12593[0m
2020-11-03T05:30:53.0834348Z      [31m       got #<Fixnum:68877> => 34438[0m
2020-11-03T05:30:53.0834697Z      [31m[0m
2020-11-03T05:30:53.0835208Z      [31m  Compared using equal?, which compares object identity,[0m
2020-11-03T05:30:53.0835863Z      [31m  but expected and actual are not the same object. Use[0m
2020-11-03T05:30:53.0836488Z      [31m  `expect(actual).to eq(expected)` if you don't care about[0m
2020-11-03T05:30:53.0837059Z      [31m  object identity in this example.[0m
2020-11-03T05:30:53.0837754Z      [36m# ./spec/rmagick/image/get_pixels_spec.rb:24:in `block (2 levels) in <top (required)>'[0m
2020-11-03T05:30:53.0838099Z 
2020-11-03T05:30:53.0838392Z   2) Magick::Image#pixel_color get/set CYMK color
2020-11-03T05:30:53.0839055Z      [31mFailure/Error: [0m[32mexpect[0m(pixel.cyan).to    equal([1;34m49[0m  * [1;34m257[0m)[0m
2020-11-03T05:30:53.0839537Z      [31m[0m
2020-11-03T05:30:53.0839946Z      [31m  expected #<Fixnum:25187> => 12593[0m
2020-11-03T05:30:53.0840383Z      [31m       got #<Fixnum:68877> => 34438[0m
2020-11-03T05:30:53.0840731Z      [31m[0m
2020-11-03T05:30:53.0841249Z      [31m  Compared using equal?, which compares object identity,[0m
2020-11-03T05:30:53.0841896Z      [31m  but expected and actual are not the same object. Use[0m
2020-11-03T05:30:53.0842501Z      [31m  `expect(actual).to eq(expected)` if you don't care about[0m
2020-11-03T05:30:53.0843067Z      [31m  object identity in this example.[0m
2020-11-03T05:30:53.0843751Z      [36m# ./spec/rmagick/image/pixel_color_spec.rb:44:in `block (2 levels) in <top (required)>'[0m
2020-11-03T05:30:53.0844104Z 
2020-11-03T05:30:53.0844431Z   3) Magick::Image#store_pixels supports CMYK color
2020-11-03T05:30:53.0845092Z      [31mFailure/Error: [0m[32mexpect[0m(pixel.cyan).to    equal([1;34m49[0m  * [1;34m257[0m)[0m
2020-11-03T05:30:53.0845572Z      [31m[0m
2020-11-03T05:30:53.0845977Z      [31m  expected #<Fixnum:25187> => 12593[0m
2020-11-03T05:30:53.0846419Z      [31m       got #<Fixnum:68877> => 34438[0m
2020-11-03T05:30:53.0846767Z      [31m[0m
2020-11-03T05:30:53.0847284Z      [31m  Compared using equal?, which compares object identity,[0m
2020-11-03T05:30:53.0847927Z      [31m  but expected and actual are not the same object. Use[0m
2020-11-03T05:30:53.0848546Z      [31m  `expect(actual).to eq(expected)` if you don't care about[0m
2020-11-03T05:30:53.0849094Z      [31m  object identity in this example.[0m
2020-11-03T05:30:53.0849956Z      [36m# ./spec/rmagick/image/store_pixels_spec.rb:39:in `block (2 levels) in <top (required)>'[0m
```

**Comment by Watson1978** [comment]
@dlemstra Do you know whether the failures in https://github.com/rmagick/rmagick/pull/1231#issuecomment-720915850 are expected behavior?

**Comment by dlemstra** [comment]
It seems that we have been ignoring the `APP14` marker for years now but I restored reading this. It seems that reading this changes the colors of the image. There is some magic happening inside the jpeg library that changes the color of the image. I just pushed a patch to restore the old behaviour.

**Comment by Watson1978** [comment]
Thanks

**Comment by Watson1978** [comment]
This PR will move to https://github.com/rmagick/rmagick/pull/1250

**Pull request closed without merging**
