### PR TITLE
Drop support for Ruby 1.8 and 1.9

### PR DESCRIPTION
**Pull request by joneslee85**
Both versions have reaches their EOL

### CODE REVIEW

**Comment by vassilevsky** [comment]
Thanks Trung! Could you also add [Ruby version specification](http://guides.rubygems.org/specification-reference/#required_ruby_version=) to gemspec?

**Comment by joneslee85** [comment]
@vassilevsky sure

**Comment by vassilevsky** [comment]
Oh, right, it simply uses the constant there. I expected it to show up in the diff and it didn't so I was confused. Sorry.

We would like the `master` branch to reflect the currently released gem. Merging this will make it look like it no longer supports Ruby 1.x. It can cause confusion.

We have a `develop` branch for all changes that will go into the next release. Could you redirect your changes there?

**Comment by joneslee85** [comment]
@vassilevsky sure. I'll do that

**Comment by vassilevsky** [comment]
Unfortunately GitHub does not allow changing a PR's target branch. I have to close this PR and you have to open a new one to the `develop` branch.

**Pull request closed without merging**
