### PR TITLE
CI: setup Github Actions for testing Windows

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by mockdeep** [comment]
@Watson1978 I'm having some trouble downloading and installing ImageMagick on Windows here. Do you have any ideas? It uses PowerShell.

https://github.com/rmagick/rmagick/pull/985/checks?check_run_id=422036057

**Comment by Watson1978** [comment]
> @Watson1978 I'm having some trouble downloading and installing ImageMagick on Windows here. Do you have any ideas? It uses PowerShell.
> 
> https://github.com/rmagick/rmagick/pull/985/checks?check_run_id=422036057

I think setup phase need silent install of ImageMagick to avoid any GUI operation with `/VERYSILENT` option.
https://github.com/rmagick/rmagick/blob/0af79a2915e9215c387f440b290c58be94c75005/.appveyor.yml#L45

**Comment by mockdeep** [comment]
@Watson1978 I added that, but it's still failing. It doesn't find the ImageMagick executable.

**Comment by Watson1978** [comment]
Hmm, the install command returns immediately until finishing installation.
The installation is doing with background.

So, maybe, need to wait some seconds (ex `sleep 5`).

**Comment by mockdeep** [comment]
Looks like [`Start-Process`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-7) has a `-Wait` flag. I'll give that a try.

**Comment by dlemstra** [comment]
Maybe you could take a look at the chocoletely (prob spelled incorrectly) script of the ImageMagick installer?

**Pull request closed without merging**
