### PR TITLE
Refactored Image#pixel_color to prepare for ImageMagick 7.

### PR DESCRIPTION
**Pull request by dlemstra**
This PR changes the implementation of `Image_pixel_color`. One of the changes is doing the check for `x` and `y` earlier to prevent issues when calling `GetVirtualPixels`. And this refactoring will also make it easier to add the changes that are necessary for ImageMagick 7.

### CODE REVIEW

**Comment by Watson1978** [comment]
I need to explain at Pull Request description because I do not know what you refactored.

**Comment by dlemstra** [comment]
Update the comment

**Comment by mockdeep** [comment]
@dlemstra do you think it would be possible to break this down into a series of separate PRs? Maybe @Watson1978 will feel differently, but I'm having a hard time parsing the different changes going on here.

**Comment by dlemstra** [comment]
The diff is not that readable because code has moved. I can try to split this up.

**Comment by Watson1978** [comment]
What kind of issue do this PR prevent?

**Comment by dlemstra** [comment]
The primary goal of this PR is to simply the code of this method. Will split this up in multiple PR's to make it more clear what is happening.

**Comment by dlemstra** [comment]
Will close this one. And the first step can be found here: #688.

**Pull request closed without merging**
