### PR TITLE
Use conversion method

### PR DESCRIPTION
**Pull request by dlemstra**
This PR makes some changes to the places where Data_Get_Struct is used but the new method Color_ToPixelColor should be used instead.

### CODE REVIEW

**Comment by Watson1978** [comment]
This PR will accept not Pixel object.
Before, following test code will raise exception. But, the code will work without exception by this.

```
require 'rmagick'

image = Magick::Image.new(20, 20)
pixels = image.get_pixels(0, 0, 1, 1)
image.tint('white', 1.0).write('test.png')
```

**Comment by Watson1978** [comment]
I think we should not merge this now. it should focus on 4.0.

**Comment by Watson1978** [comment]
At least, this PR should provides test codes about behavior changes.

**Comment by dlemstra** [comment]
I did not realize that these changes would add some extra features. I have just pushed an extra commit that adds tests for the tint method.

Why did you mark this as 4.0? The change is not a breaking change. The old behavior continued to work, this PR now adds extra functionality by also allowing a string.

**Comment by Watson1978** [comment]
I don't like to add behavior changing into maintenance version.

**Comment by mockdeep** [comment]
Hmm, it sounds like this won't break existing behavior, unless somebody was depending on it throwing an error. Is that correct? I don't think users depending on the error is a supported use-case, so if my understanding is correct I'd probably put this in a minor release, since it seems like it adds functionality without breaking anything existing. Per [SemVer](https://semver.org/):

major version (3.0.0 -> 4.0.0): breaking changes (dropping support for ruby/IM versions, removing exisiting APIs, changing existing APIs in a way that would break existing code)
minor version (3.0.0 -> 3.1.0): new features (supporting new ruby/IM versions, adding new APIs, enhancing existing APIs without breaking existing code)
patch version (3.0.0 -> 3.0.1): bug fixes (fix memory leaks, SEGV, (I also include refactors under here))

**Comment by Watson1978** [comment]
@mockdeep Thanks. This PR should ship with minor update.

**Pull request merged**
