### PR TITLE
CI: Use preinstalled ruby in Travis

### PR DESCRIPTION
**Pull request by Watson1978**
By using preinstalled ruby, we will cut a time to set up Ruby in Travis.

* Before
22.36 sec
before

* After
0.87 sec
after

Travis pre-installed following Ruby versions.
* ruby-2.3.8
* ruby-2.4.5
* ruby-2.5.3

https://travis-ci.org/rmagick/rmagick/jobs/528851394#L154
ruby

### CODE REVIEW

**Comment by Watson1978** [comment]
@mockdeep What do you think about this ?

**Comment by mockdeep** [comment]
@Watson1978 this seems good. I wonder if we also want to [cache the RVM dependencies](https://docs.travis-ci.com/user/caching/#cache-rvm-ruby-version-for-non-ruby-projects)?

**Comment by Watson1978** [comment]
@mockdeep Thank you for your check. 
In this project, Travis CI works
1. set up Ruby
2. restore the cache

So, If Travis could restore the cache at first,  we can use the technique, I think...

**Comment by mockdeep** [comment]
@Watson1978 hmm, yeah, you're right. That's really strange. It looks like they have one cache per version of Ruby, so they restore it after setting the Ruby version. I don't think we'd be able to cache RVM unless we switched to using RVM in our setup script instead of configuring it in `.travis.yml`. That seems pretty bad, though. I think this will do for now.

**Pull request merged**
