### PR TITLE
remove style checks from Travis build

### PR DESCRIPTION
**Pull request by mockdeep**

### CODE REVIEW

**Comment by mockdeep** [comment]
I kind of like the idea of using RSpec as a model for contributions. They don't accept pulls without tests, and run rubocop with their build. Seems like they run a pretty clean machine.

**Comment by vassilevsky** [comment]
Could you also remove `STYLE_CHECKS` from `Rakefile`?

I will read their guidelines.

**Comment by vassilevsky** [comment]
Yeah, their checklist is quite comprehensive.

I think we need to add this coverage thing to Code Climate. I'll look into it ASAP.

**Comment by mockdeep** [comment]
I'd like to have a way to run rubocop as part of a comprehensive build locally, which is why I left that in the `Rakefile`. Do you have a thought on another way to handle that?

**Comment by vassilevsky** [comment]
Oh, I get it. Alright then.

**Pull request merged**
