### PR TITLE
Add failing spec for Draw#get_type_metrics

### PR DESCRIPTION
**Pull request by latortuga**
This method should allow sending an @ character as the first character. References rmagick-temp/rmagick/issues/135

### CODE REVIEW

**Comment by vassilevsky** [comment]
Thank you! 💪

**Comment by latortuga** [comment]
Any way I can help get this resolved? We run into this on a monthly basis and are itching for a resolution. :smile: :+1:

**Comment by bf4** [comment]
I see some specs failing, `expected no Exception, got #<ArgumentError: no text to measure>`

**Comment by latortuga** [comment]
@bf4 https://github.com/rmagick-temp/rmagick/issues/135#issuecomment-105476565

**Comment by latortuga** [comment]
@bf4 basically this is a failing test for what we think is an issue with Rmagick. I'm not 100% clear if it is an issue or expected behavior. Basically, here's the minimal ruby reproduction:

```ruby
> Magick::Version
=> "RMagick 2.15.0"

d = Magick::Draw.new
d.get_type_metrics("@") # => ArgumentError: no text to measure
d.get_type_metrics("@thing") # => ArgumentError: no text to measure
d.get_type_metrics("thing@") # => works
```

Since an '@' seems to work fine in the middle of a string, it seems like it should work fine at the beginning. This PR is merely a failing spec to demonstrate the issue so that it can be fixed.

**Comment by latortuga** [comment]
Good news and bad news, I actually dove in a little bit and finally figured out the cause of this. The '@' character, when it appears at the beginning of a string, indicates that a file should be included. So if you want it in the string as an actual '@' character, it needs to be escaped. [Per the ImageMagick docs](http://www.imagemagick.org/Usage/text/#escape_chars), this seems to be expected behavior.

**Pull request closed without merging**
