### PR TITLE
Rubocop: configure Style/TrailingCommaInArguments

### PR DESCRIPTION
**Pull request by mockdeep**
This changes the setting to require trailing commas in method arguments.

The primary benefit of this approach is that it reduces diff noise when
we add/remove an item from a list:

```diff
 {
-  a: 'a'
+  a: 'a',
+  b: 'b'
 }
```

vs:

```diff
 {
   a: 'a',
+  b: 'b',
 }
```

It also preserves the `git blame` on the previous line. In addition, it
has some benefits in terms of developer ergonomics. You no longer have
to remember the comma when you add/remove an item, copy/paste, or sort a
list. It's a minor tripping point, but I often have this sort of problem
working in codebases where the trailing comma is not used. Then I don't
find out about it until the tests run, or worst case it makes it into
production and we get a syntax error.

https://rubocop.readthedocs.io/en/stable/cops_style/#styletrailingcommainarguments

### CODE REVIEW

**Comment by mockdeep** [comment]
@dlemstra I had the same reaction when I first came across this style. I added a lot more explanation to the commit message above in case that might sway you more. It's hard to get a good measure on what the Ruby community uses as a whole. The [Ruby Style Guide][1] actually recommends against it, but there has a been [a long debate][2] about it as well. That being said, I'd argue we shouldn't worry as much about how popular it is, but instead about the reasons they provide for one approach or the other.

[1]: https://github.com/rubocop-hq/ruby-style-guide#no-trailing-params-comma
[2]: https://github.com/rubocop-hq/ruby-style-guide/issues/273

**Comment by dlemstra** [comment]
Still not a fan of this still but I will let you decide 😄

**Comment by mockdeep** [comment]
@Watson1978 what do you think?

**Comment by Watson1978** [comment]
I don't like it, but either is fine :)

**Comment by mockdeep** [comment]
Okay, sounds like I'm outvoted.

**Pull request closed without merging**
