### PR TITLE
Convert more tests to specs

### PR DESCRIPTION
**Pull request by mockdeep**
I went with a file for the method here. There are a buttload of `Image`
specs and it seems like the better option to having a 6000 line spec
file.

### CODE REVIEW

**Comment by mockdeep** [comment]
btw, I don't have access to the `rmagick/rmagick` repo. Had to push up to my own remote.

**Comment by bf4** [comment]
@mockdeep You should have an invite to the org now.

**Comment by vassilevsky** [comment]
This pull request illustrates the problem with RuboCop. Robert has done awesome job with the spec. Actual tests have passed. (The one randomly failing test has failed but that's OK.) Yet the pull request status is all red. It scares the hell out of maintainers and creates a barrier to merging.

I suggest that we remove RuboCop from Travis.

I love the tool, but it's a nice-to-have, not a requirement.

**Comment by mockdeep** [comment]
I actually prefer it to be there so that I know how to make sure I match the prevailing style of the repo. It's a little awkward here because it's running on pre-existing code, which isn't ideal. That's why I had disabled all of the rules originally. It looks like maybe rubocop just added some new rules that need to be accounted for.

**Comment by bf4** [comment]
Or, rubocop could 

1. not run on CI
1. not fail CI
1. run with its own status 
  - e.g. with houndci, which could also add comments to the pr
  - or when it fails, make a curl request to the github status

**Comment by mockdeep** [comment]
My problem with hound is that it's so noisy and spams all of the contributors. It's also not necessarily going to have parity with rubocop, since it updates at a different/slower pace. I could see having a separate build that just runs rubocop, though, as a different check.

**Comment by vassilevsky** [comment]
I like the idea that it runs as a separate check. This way we will clearly see tests and RuboCop as two separate entries in the checks box.

**Pull request merged**
