### PR TITLE
CI: reintroduce CircleCI

### PR DESCRIPTION
**Pull request by mockdeep**
Github Actions has been very flaky, so this brings back CircleCI.

### CODE REVIEW

**Comment by mockdeep** [comment]
I'm planning on running this 10 or so times to see if/how flaky it is on CircleCI.

**Comment by mockdeep** [comment]
@Watson1978 @dlemstra I re-ran the build on CircleCI [10 times](https://circleci.com/gh/rmagick/workflows/rmagick/tree/rf-circle_again) and it seems to pass consistently. Should we switch back to CircleCI for now? It takes around 25 minutes to run all of the jobs there.

**Comment by Watson1978** [comment]
There is no problem If CircleCI is executed when the PR is created :)

**Comment by mockdeep** [comment]
@dlemstra are you able to view the build if you log into CircleCI with your Github credentials?

@Watson1978 I disabled the build notifications while I'm working on this, but I'll re-enable them when we're happy with the setup.

**Comment by mockdeep** [comment]
@Watson1978 @dlemstra if the build is flaky on Ruby 2.6, IM 6.7/6.8, is there any way we can figure out what is causing it? Maybe it's a legitimate issue, a memory leak or something.

**Comment by Watson1978** [comment]
If my guess is correct in https://github.com/rmagick/rmagick/pull/1084, it will be solved by https://github.com/rmagick/rmagick/pull/1085

**Pull request closed without merging**
