### PR TITLE
Removed duplicate code to determine the old color.

### PR DESCRIPTION
**Pull request by dlemstra**

### CODE REVIEW

**Comment by Watson1978** [comment]
Where is the duplicate code?

**Comment by dlemstra** [comment]
There is code to determine the `old_color` and this is now happening at two places. The first `if (!set)` block does almost the same as what is happening inside the code block where the pixel is changed. And with some extra conditions we don't need to get the pixel in two code blocks.

**Comment by dlemstra** [comment]
Get and set aren't really that different. Both paths will return the value of the previous pixel. The only difference is that set path also changes that pixel. And creating two different functions will not make this any better it will even hide the duplicate code.

**Comment by Watson1978** [comment]
> Get and set aren't really that different

I don't think so.

**Comment by dlemstra** [comment]
This method does both a get and a set in the same method and when the pixel is set it also executes code that is almost similar to the get path. But it seems you want to keep separate paths with duplicate code instead. Will close this PR and preserve this behavior.

**Pull request closed without merging**
